FROM tiangolo/nginx-rtmp

COPY nginx.conf /etc/nginx/nginx.conf
COPY src/index.html /www/
COPY src/main.js /www/
COPY src/HlsObject.js /www/
COPY src/styles.css /www/
COPY src/videoTag.js /www/
COPY src/createHLS.js /www/